# Config file for predict.py
# model path to load the trained model
MODEL_PATH: "output/mnist_resnet.pt"
# image path to load for classification
IMAGE_PATH: "data/t10k-images-idx3-ubyte_dir/image_1003.png"
